
package fr.polytech;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceEtudiantService", targetNamespace = "http://www.polytech.fr", wsdlLocation = "file:/C:/Users/HEILMANN%20Brice/eclipse-workspace/ClientJavaTP2/src/ServiceEtudiantService.wsdl")
public class ServiceEtudiantService
    extends Service
{

    private final static URL SERVICEETUDIANTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.polytech.ServiceEtudiantService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.polytech.ServiceEtudiantService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/HEILMANN%20Brice/eclipse-workspace/ClientJavaTP2/src/ServiceEtudiantService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/HEILMANN%20Brice/eclipse-workspace/ClientJavaTP2/src/ServiceEtudiantService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEETUDIANTSERVICE_WSDL_LOCATION = url;
    }

    public ServiceEtudiantService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceEtudiantService() {
        super(SERVICEETUDIANTSERVICE_WSDL_LOCATION, new QName("http://www.polytech.fr", "ServiceEtudiantService"));
    }

    /**
     * 
     * @return
     *     returns ServiceEtudiant
     */
    @WebEndpoint(name = "ServiceEtudiantPort")
    public ServiceEtudiant getServiceEtudiantPort() {
        return super.getPort(new QName("http://www.polytech.fr", "ServiceEtudiantPort"), ServiceEtudiant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceEtudiant
     */
    @WebEndpoint(name = "ServiceEtudiantPort")
    public ServiceEtudiant getServiceEtudiantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.fr", "ServiceEtudiantPort"), ServiceEtudiant.class, features);
    }

}
