
package fr.polytech;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GestionEtudiantsService", targetNamespace = "http://www.polytech.fr", wsdlLocation = "file:/D:/sam54/Documents/GitHub/Projet4ASIR_HEILMANN_AUDIFFRET/Cours_Audiffret/TP1_SOAP/ClientJavaGestionEtudiant/src/GestionEtudiantsService.wsdl")
public class GestionEtudiantsService
    extends Service
{

    private final static URL GESTIONETUDIANTSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.polytech.GestionEtudiantsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.polytech.GestionEtudiantsService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/sam54/Documents/GitHub/Projet4ASIR_HEILMANN_AUDIFFRET/Cours_Audiffret/TP1_SOAP/ClientJavaGestionEtudiant/src/GestionEtudiantsService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/sam54/Documents/GitHub/Projet4ASIR_HEILMANN_AUDIFFRET/Cours_Audiffret/TP1_SOAP/ClientJavaGestionEtudiant/src/GestionEtudiantsService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTIONETUDIANTSSERVICE_WSDL_LOCATION = url;
    }

    public GestionEtudiantsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionEtudiantsService() {
        super(GESTIONETUDIANTSSERVICE_WSDL_LOCATION, new QName("http://www.polytech.fr", "GestionEtudiantsService"));
    }

    /**
     * 
     * @return
     *     returns GestionEtudiants
     */
    @WebEndpoint(name = "GestionEtudiantsPort")
    public GestionEtudiants getGestionEtudiantsPort() {
        return super.getPort(new QName("http://www.polytech.fr", "GestionEtudiantsPort"), GestionEtudiants.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionEtudiants
     */
    @WebEndpoint(name = "GestionEtudiantsPort")
    public GestionEtudiants getGestionEtudiantsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.fr", "GestionEtudiantsPort"), GestionEtudiants.class, features);
    }

}
