
package fr.polytech;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GestionEtudiants", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionEtudiants {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initialisation", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Initialisation")
    @ResponseWrapper(localName = "initialisationResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.InitialisationResponse")
    public void initialisation();

    /**
     * 
     * @param specialite
     * @param prenom
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajout", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Ajout")
    @ResponseWrapper(localName = "ajoutResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjoutResponse")
    public String ajout(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "specialite", targetNamespace = "")
        String specialite);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SearchId")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchId", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SearchId")
    @ResponseWrapper(localName = "SearchIdResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SearchIdResponse")
    public String searchId(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param specialite
     * @param prenom
     * @param id
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifier", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Modifier")
    @ResponseWrapper(localName = "modifierResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.ModifierResponse")
    public String modifier(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "specialite", targetNamespace = "")
        String specialite);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tous", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Tous")
    @ResponseWrapper(localName = "tousResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.TousResponse")
    public String tous();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "suppression", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Suppression")
    @ResponseWrapper(localName = "suppressionResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SuppressionResponse")
    public void suppression(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
