
package fr.polytech;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceEtudiant", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceEtudiant {


    /**
     * 
     * @return
     *     returns java.util.List<fr.polytech.Etudiant>
     */
    @WebMethod(operationName = "creer_liste")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creer_liste", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.CreerListe")
    @ResponseWrapper(localName = "creer_listeResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.CreerListeResponse")
    public List<Etudiant> creerListe();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fr.polytech.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tous", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Tous")
    @ResponseWrapper(localName = "tousResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.TousResponse")
    public List<Etudiant> tous(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Etudiant> arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.polytech.Etudiant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajout", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Ajout")
    @ResponseWrapper(localName = "ajoutResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjoutResponse")
    public Etudiant ajout(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        List<Etudiant> arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.polytech.Etudiant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recherche", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Recherche")
    @ResponseWrapper(localName = "rechercheResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.RechercheResponse")
    public Etudiant recherche(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Etudiant> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimer", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Supprimer")
    @ResponseWrapper(localName = "supprimerResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SupprimerResponse")
    public boolean supprimer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Etudiant> arg1);

}
