
package gestion;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GestionComptes", targetNamespace = "http://gestion/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionComptes {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initialisation", targetNamespace = "http://gestion/", className = "gestion.Initialisation")
    @ResponseWrapper(localName = "initialisationResponse", targetNamespace = "http://gestion/", className = "gestion.InitialisationResponse")
    public void initialisation();

    /**
     * 
     * @param prenom
     * @param mail
     * @param mdp
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajoutCompte", targetNamespace = "http://gestion/", className = "gestion.AjoutCompte")
    @ResponseWrapper(localName = "ajoutCompteResponse", targetNamespace = "http://gestion/", className = "gestion.AjoutCompteResponse")
    public void ajoutCompte(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "mail", targetNamespace = "")
        String mail,
        @WebParam(name = "mdp", targetNamespace = "")
        String mdp);

    /**
     * 
     * @param mail
     * @return
     *     returns gestion.Compte
     */
    @WebMethod(operationName = "SearchCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchCompte", targetNamespace = "http://gestion/", className = "gestion.SearchCompte")
    @ResponseWrapper(localName = "SearchCompteResponse", targetNamespace = "http://gestion/", className = "gestion.SearchCompteResponse")
    public Compte searchCompte(
        @WebParam(name = "mail", targetNamespace = "")
        String mail);

    /**
     * 
     * @return
     *     returns java.util.List<gestion.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tous", targetNamespace = "http://gestion/", className = "gestion.Tous")
    @ResponseWrapper(localName = "tousResponse", targetNamespace = "http://gestion/", className = "gestion.TousResponse")
    public List<Compte> tous();

}
